using System;
// ReSharper disable StringLiteralTypo

namespace FF8
{
    public static class AreaName
    {
        public static String Get(Int32 areaId)
        {
            if (areaId >= 0 && areaId < _names.Length)
                return _names[areaId];

            return $"Unknown area: {areaId}";
        }

        private static readonly String[] _names =
        {
            /* [000] */ "???",
            /* [001] */ "{Term Balamb}- Alcauld Plains",
            /* [002] */ "{Term Balamb}- Gaulg Mountains",
            /* [003] */ "{Term Balamb}- Rinaul Coast",
            /* [004] */ "{Term Balamb}- Raha Cape",
            /* [005] */ "{Term Timber}- Roshfall Forest",
            /* [006] */ "{Term Timber}- Mandy Beach",
            /* [007] */ "{Term Timber}- Obel Lake",
            /* [008] */ "{Term Timber}- Lanker Plains",
            /* [009] */ "{Term Timber}- Nanchucket Island",
            /* [010] */ "{Term Timber}- Yaulny Canyon",
            /* [011] */ "{Term Dollet}- Hasberry Plains",
            /* [012] */ "{Term Dollet}- Holy Glory Cape",
            /* [013] */ "{Term Dollet}- Long Horn Island",
            /* [014] */ "{Term Dollet}- Malgo Peninsula",
            /* [015] */ "{Term Galbadia}- Monterosa Plateau",
            /* [016] */ "{Term Galbadia}- Lallapalooza Canyon",
            /* [017] */ "{Term Timber}- Shenand Hill",
            /* [018] */ "{Term Galbadia}- Gotland Peninsula",
            /* [019] */ "Island Closest to Hell",
            /* [020] */ "Great Plains of {Term Galbadia}",
            /* [021] */ "{Term Galbadia}- Wilburn Hill",
            /* [022] */ "{Term Galbadia}- Rem Archipelago",
            /* [023] */ "{Term Galbadia}- Dingo Desert",
            /* [024] */ "Winhill- Winhill Bluffs",
            /* [025] */ "Winhill- Humphrey Archipelago",
            /* [026] */ "{Term Trabia}- Winter Island",
            /* [027] */ "{Term Trabia}- Sorbald Snowfield",
            /* [028] */ "{Term Trabia}- Eldbeak Peninsula",
            /* [029] */ "               ",
            /* [030] */ "{Term Trabia}- Hawkwind Plains",
            /* [031] */ "{Term Trabia}- Albatross Archipelago",
            /* [032] */ "{Term Trabia}- Bika Snowfield",
            /* [033] */ "{Term Trabia}- Thor Peninsula",
            /* [034] */ "               ",
            /* [035] */ "{Term Trabia}- Heath Peninsula",
            /* [036] */ "{Term Trabia}- {Term Trabia} Crater",
            /* [037] */ "{Term Trabia}- Vienne Mountains",
            /* [038] */ "{Term Esthar}- Mordred Plains",
            /* [039] */ "{Term Esthar}- Nortes Mountains",
            /* [040] */ "{Term Esthar}- Fulcura Archipelago",
            /* [041] */ "{Term Esthar}- Grandidi Forest",
            /* [042] */ "{Term Esthar}- Millefeuille Archipelago",
            /* [043] */ "Great Plains of {Term Esthar}",
            /* [044] */ "{Term Esthar} City",
            /* [045] */ "{Term Esthar}- Great Salt Lake",
            /* [046] */ "{Term Esthar}- West Coast",
            /* [047] */ "{Term Esthar}- Sollet Mountains",
            /* [048] */ "{Term Esthar}- Abadan Plains",
            /* [049] */ "{Term Esthar}- Minde Island",
            /* [050] */ "{Term Esthar}- Kashkabald Desert",
            /* [051] */ "Island Closest to Heaven",
            /* [052] */ "{Term Esthar}- Talle Mountains",
            /* [053] */ "{Term Esthar}- Shalmal Peninsula",
            /* [054] */ "{Term Centra}- Lolestern Plains",
            /* [055] */ "{Term Centra}- Almaj Mountains",
            /* [056] */ "{Term Centra}- Lenown Plains",
            /* [057] */ "{Term Centra}- Cape of Good Hope",
            /* [058] */ "{Term Centra}- Yorn Mountains",
            /* [059] */ "{Term Esthar}- Cactuar Island",
            /* [060] */ "{Term Centra}- Serengetti Plains",
            /* [061] */ "{Term Centra}- Nectar Peninsula",
            /* [062] */ "{Term Centra}- {Term Centra} Crater",
            /* [063] */ "{Term Centra}- Poccarahi Island",
            /* [064] */ "B-{Term Garden}- Library",
            /* [065] */ "B-{Term Garden}- Front Gate",
            /* [066] */ "B-{Term Garden}- Classroom",
            /* [067] */ "B-{Term Garden}- Cafeteria",
            /* [068] */ "B-{Term Garden}- MD Level",
            /* [069] */ "B-{Term Garden}- 2F Hallway",
            /* [070] */ "B-{Term Garden}- Hall",
            /* [071] */ "B-{Term Garden}- Infirmary",
            /* [072] */ "B-{Term Garden}- Dormitory Double",
            /* [073] */ "B-{Term Garden}- Dormitory Single",
            /* [074] */ "B-{Term Garden}- Headmaster’s Office",
            /* [075] */ "B-{Term Garden}- Parking Lot",
            /* [076] */ "B-{Term Garden}- Ballroom",
            /* [077] */ "B-{Term Garden}- Quad",
            /* [078] */ "B-{Term Garden}- Training Center",
            /* [079] */ "B-{Term Garden}- Secret Area",
            /* [080] */ "B-{Term Garden}- Hallway",
            /* [081] */ "B-{Term Garden}- Master Room",
            /* [082] */ "B-{Term Garden}- Deck",
            /* [083] */ "{Term Balamb}- The Dincht’s",
            /* [084] */ "{Term Balamb} Hotel",
            /* [085] */ "{Term Balamb}- Town Square",
            /* [086] */ "{Term Balamb}- Station Yard",
            /* [087] */ "{Term Balamb} Harbor",
            /* [088] */ "{Term Balamb}- Residence",
            /* [089] */ "Train",
            /* [090] */ "Car",
            /* [091] */ "Inside Ship",
            /* [092] */ "Fire Cavern",
            /* [093] */ "{Term Dollet}- Town Square",
            /* [094] */ "{Term Dollet}- Lapin Beach",
            /* [095] */ "{Term Dollet} Harbor",
            /* [096] */ "{Term Dollet} Pub",
            /* [097] */ "{Term Dollet} Hotel",
            /* [098] */ "{Term Dollet}- Residence",
            /* [099] */ "{Term Dollet}- Comm Tower",
            /* [100] */ "{Term Dollet}- Mountain Hideout",
            /* [101] */ "{Term Timber}- City Square",
            /* [102] */ "{Term Timber} TV Station",
            /* [103] */ "{Term Timber}- Forest Owls’ Base",
            /* [104] */ "{Term Timber} Pub",
            /* [105] */ "{Term Timber} Hotel",
            /* [106] */ "{Term Timber}- Train",
            /* [107] */ "{Term Timber}- Residence",
            /* [108] */ "{Term Timber}- TV Screen",
            /* [109] */ "{Term Timber}- Editorial Department",
            /* [110] */ "{Term Timber} Forest",
            /* [111] */ "{Term Galbadia} {Term Garden}- Front Gate",
            /* [112] */ "G-{Term Garden}- Station",
            /* [113] */ "G-{Term Garden}- Hall",
            /* [114] */ "G-{Term Garden}- Hallway",
            /* [115] */ "G-{Term Garden}- Reception Room",
            /* [116] */ "G-{Term Garden}- Classroom",
            /* [117] */ "G-{Term Garden}- Clubroom",
            /* [118] */ "G-{Term Garden}- Dormitory",
            /* [119] */ "G-{Term Garden}- Elevator Hall",
            /* [120] */ "G-{Term Garden}- Master Room",
            /* [121] */ "G-{Term Garden}- Auditorium",
            /* [122] */ "G-{Term Garden}- Athletic Track",
            /* [123] */ "G-{Term Garden}- Stand",
            /* [124] */ "G-{Term Garden}- Back Entrance",
            /* [125] */ "G-{Term Garden}- Gymnasium",
            /* [126] */ "{Term Deling}- Presidential Residence",
            /* [127] */ "{Term DelingCity}- Caraway’s Mansion",
            /* [128] */ "{Term DelingCity}- Station Yard",
            /* [129] */ "{Term DelingCity}- City Square",
            /* [130] */ "{Term DelingCity}- Hotel",
            /* [131] */ "{Term DelingCity}- Club",
            /* [132] */ "{Term DelingCity}- Gateway",
            /* [133] */ "{Term DelingCity}- Parade",
            /* [134] */ "{Term DelingCity}- Sewer",
            /* [135] */ "{Term Galbadia} D-District Prison",
            /* [136] */ "Desert",
            /* [137] */ "{Term Galbadia} Missile Base",
            /* [138] */ "Winhill Village",
            /* [139] */ "Winhill Pub",
            /* [140] */ "Winhill- Vacant House",
            /* [141] */ "Winhill- Mansion",
            /* [142] */ "Winhill- Residence",
            /* [143] */ "Winhill- Hotel",
            /* [144] */ "Winhill- Car",
            /* [145] */ "Tomb of the Unknown King",
            /* [146] */ "{Term FishermansHorizon}",
            /* [147] */ "FH- Residential Area",
            /* [148] */ "FH- Sun Panel",
            /* [149] */ "FH- Mayor’s Residence",
            /* [150] */ "FH- Factory",
            /* [151] */ "FH- Festival Grounds",
            /* [152] */ "FH- Hotel",
            /* [153] */ "FH- Residence",
            /* [154] */ "FH- Station Yard",
            /* [155] */ "Horizon Bridge",
            /* [156] */ "Seaside Station",
            /* [157] */ "Great Salt Lake",
            /* [158] */ "Mystery Building",
            /* [159] */ "{Term Esthar}- City",
            /* [160] */ "{Term Esthar}- Odine’s Laboratory",
            /* [161] */ "{Term Esthar}- Airstation",
            /* [162] */ "Lunatic Pandora Approaching",
            /* [163] */ "{Term Esthar}- Presidential Palace",
            /* [164] */ "Presidential Palace- Hall",
            /* [165] */ "Presidential Palace- Hallway",
            /* [166] */ "Presidential Palace- Office",
            /* [167] */ "Dr. Odine’s Laboratory- Lobby",
            /* [168] */ "Dr. Odine’s Laboratory- Lab",
            /* [169] */ "Deleted",
            /* [170] */ "{Term LunarGate}",
            /* [171] */ "{Term LunarGate}- Concourse",
            /* [172] */ "{Term LunarGate}- Deep Freeze",
            /* [173] */ "{Term Esthar} Sorceress Memorial",
            /* [174] */ "Sorceress Memorial- Entrance",
            /* [175] */ "Sorceress Memorial- Pod",
            /* [176] */ "Sorceress Memorial- Ctrl Room",
            /* [177] */ "Tears’ Point",
            /* [178] */ "Lunatic Pandora Laboratory",
            /* [179] */ "Emergency Landing Zone",
            /* [180] */ "Spaceship Landing Zone",
            /* [181] */ "Lunatic Pandora",
            /* [182] */ "{Term Centra}- Excavation Site",
            /* [183] */ "Edea’s House",
            /* [184] */ "Edea’s House- Playroom",
            /* [185] */ "Edea’s House- Bedroom",
            /* [186] */ "Edea’s House- Backyard",
            /* [187] */ "Edea’s House- Oceanside",
            /* [188] */ "Edea’s House- Flower Field",
            /* [189] */ "{Term Centra} Ruins",
            /* [190] */ "{Term Trabia} {Term Garden}- Front Gate",
            /* [191] */ "T-{Term Garden}- Cemetery",
            /* [192] */ "T-{Term Garden}- Garage",
            /* [193] */ "T-{Term Garden}- Festival Stage",
            /* [194] */ "T-{Term Garden}- Classroom",
            /* [195] */ "T-{Term Garden}- Athletic Ground",
            /* [196] */ "Mystery Dome",
            /* [197] */ "{Term ShumiVillage}- Desert Village",
            /* [198] */ "{Term ShumiVillage}- Elevator",
            /* [199] */ "{Term ShumiVillage}- Village",
            /* [200] */ "{Term ShumiVillage}- Residence",
            /* [201] */ "{Term ShumiVillage}- Residence",
            /* [202] */ "{Term ShumiVillage}- Residence",
            /* [203] */ "{Term ShumiVillage}- Hotel",
            /* [204] */ "{Term Trabia} Canyon",
            /* [205] */ "White SeeD Ship",
            /* [206] */ "White SeeD Ship",
            /* [207] */ "White SeeD Ship- Cabin",
            /* [208] */ "Ragnarok- Cockpit",
            /* [209] */ "Ragnarok- Passenger Seat",
            /* [210] */ "Ragnarok- Aisle",
            /* [211] */ "Ragnarok- Hangar",
            /* [212] */ "Ragnarok- Entrance",
            /* [213] */ "Ragnarok- Air Room",
            /* [214] */ "Ragnarok- Space Hatch",
            /* [215] */ "Deep Sea Research Center",
            /* [216] */ "Deep Sea Research Center- Lb",
            /* [217] */ "Deep Sea Research Center- Lv",
            /* [218] */ "Deep Sea Deposit",
            /* [219] */ "{Term LunarBase}- Control Room",
            /* [220] */ "{Term LunarBase}- Medical Room",
            /* [221] */ "{Term LunarBase}- Pod",
            /* [222] */ "{Term LunarBase}- Dock",
            /* [223] */ "{Term LunarBase}- Passageway",
            /* [224] */ "{Term LunarBase}- Locker",
            /* [225] */ "{Term LunarBase}- Residential Zone",
            /* [226] */ "Outer Space",
            /* [227] */ "Chocobo Forest",
            /* [228] */ "Wilderness",
            /* [229] */ "{Term UltimeciaCastle}- Hall",
            /* [230] */ "{Term UltimeciaCastle}- Grand Hall",
            /* [231] */ "{Term UltimeciaCastle}- Terrace",
            /* [232] */ "{Term UltimeciaCastle}- Wine Cellar",
            /* [233] */ "{Term UltimeciaCastle}- Passageway",
            /* [234] */ "{Term UltimeciaCastle}- Elevator Hall",
            /* [235] */ "{Term UltimeciaCastle}- Stairway Hall",
            /* [236] */ "{Term UltimeciaCastle}- Treasure Rm",
            /* [237] */ "{Term UltimeciaCastle}- Storage Room",
            /* [238] */ "{Term UltimeciaCastle}- Art Gallery",
            /* [239] */ "{Term UltimeciaCastle}- Flood Gate",
            /* [240] */ "{Term UltimeciaCastle}- Armory",
            /* [241] */ "{Term UltimeciaCastle}- Prison Cell",
            /* [242] */ "{Term UltimeciaCastle}- Waterway",
            /* [243] */ "{Term UltimeciaCastle}- Courtyard",
            /* [244] */ "{Term UltimeciaCastle}- Chapel",
            /* [245] */ "{Term UltimeciaCastle}- Clock Tower",
            /* [246] */ "{Term UltimeciaCastle}- Master Room",
            /* [247] */ "???",
            /* [248] */ "{Term UltimeciaCastle}",
            /* [249] */ "Commencement Room",
            /* [250] */ "Queen"
        };
    }
}