using System;
using System.Collections.Generic;


namespace OpenVIII
{
    public abstract class JsmInstruction : IJsmInstruction, IFormattableScript
    {
        protected JsmInstruction()
        {
        }

        public virtual void Format(ScriptWriter sw, IScriptFormatterContext formatterContext, IServices services)
        {
            sw.AppendLine(this.ToString());
        }

        public virtual IAwaitable Execute(IServices services)
        {
            return TestExecute(services);
        }

        public virtual IAwaitable TestExecute(IServices services)
        {
            throw new NotImplementedException($"The instruction {GetType()} is not implemented yet. Please override \"{nameof(Execute)}\" method if you know the correct behavior or \"{nameof(TestExecute)}\" method for test environment.");
        }

        public static JsmInstruction TryMake(Jsm.Opcode opcode, Int32 parameter, IStack<IJsmExpression> stack)
        {
            if (Factories.TryGetValue(opcode, out var make))
                return make(parameter, stack);

            return null;
        }

        private delegate JsmInstruction Make(Int32 parameter, IStack<IJsmExpression> stack);

        private static readonly Dictionary<Jsm.Opcode, Make> Factories = new Dictionary<Jsm.Opcode, Make>
        {
            {Jsm.Opcode.AASK, (p, s) => new AASK(p, s)},
            {Jsm.Opcode.NOP, (p, s) => new NOP(p, s)},
            {Jsm.Opcode.JMP, (p, s) => new JMP(p, s)},
            {Jsm.Opcode.JPF, (p, s) => new JPF(p, s)},
            //{Opcode.GJMP, (p, s) => new GJMP(p, s)},
            {Jsm.Opcode.LBL, (p, s) => new LBL(p, s)},
            {Jsm.Opcode.RET, (p, s) => new IRET(p, s)},
            {Jsm.Opcode.POPI_L, (p, s) => new POPI_L(p, s)},
            {Jsm.Opcode.POPM_B, (p, s) => new POPM_B(p, s)},
            {Jsm.Opcode.POPM_W, (p, s) => new POPM_W(p, s)},
            {Jsm.Opcode.POPM_L, (p, s) => new POPM_L(p, s)},
            {Jsm.Opcode.REQ, (p, s) => new REQ(p, s)},
            {Jsm.Opcode.REQSW, (p, s) => new REQSW(p, s)},
            {Jsm.Opcode.REQEW, (p, s) => new REQEW(p, s)},
            {Jsm.Opcode.PREQ, (p, s) => new PREQ(p, s)},
            {Jsm.Opcode.PREQSW, (p, s) => new PREQSW(p, s)},
            {Jsm.Opcode.PREQEW, (p, s) => new PREQEW(p, s)},
            {Jsm.Opcode.UNUSE, (p, s) => new UNUSE(p, s)},
            //{Opcode.DEBUG, (p, s) => new DEBUG(p, s)},
            {Jsm.Opcode.HALT, (p, s) => new HALT(p, s)},
            {Jsm.Opcode.SET, (p, s) => new SET(p, s)},
            {Jsm.Opcode.SET3, (p, s) => new SET3(p, s)},
            {Jsm.Opcode.IDLOCK, (p, s) => new IDLOCK(p, s)},
            {Jsm.Opcode.IDUNLOCK, (p, s) => new IDUNLOCK(p, s)},
            {Jsm.Opcode.EFFECTPLAY2, (p, s) => new EFFECTPLAY2(p, s)},
            {Jsm.Opcode.FOOTSTEP, (p, s) => new FOOTSTEP(p, s)},
            {Jsm.Opcode.JUMP, (p, s) => new JUMP(p, s)},
            {Jsm.Opcode.JUMP3, (p, s) => new JUMP3(p, s)},
            {Jsm.Opcode.LADDERUP, (p, s) => new LADDERUP(p, s)},
            {Jsm.Opcode.LADDERDOWN, (p, s) => new LADDERDOWN(p, s)},
            {Jsm.Opcode.LADDERUP2, (p, s) => new LADDERUP2(p, s)},
            {Jsm.Opcode.LADDERDOWN2, (p, s) => new LADDERDOWN2(p, s)},
            {Jsm.Opcode.MAPJUMP, (p, s) => new MAPJUMP(p, s)},
            {Jsm.Opcode.MAPJUMP3, (p, s) => new MAPJUMP3(p, s)},
            {Jsm.Opcode.SETMODEL, (p, s) => new SETMODEL(p, s)},
            {Jsm.Opcode.BASEANIME, (p, s) => new BASEANIME(p, s)},
            {Jsm.Opcode.ANIME, (p, s) => new ANIME(p, s)},
            {Jsm.Opcode.ANIMEKEEP, (p, s) => new ANIMEKEEP(p, s)},
            {Jsm.Opcode.CANIME, (p, s) => new CANIME(p, s)},
            {Jsm.Opcode.CANIMEKEEP, (p, s) => new CANIMEKEEP(p, s)},
            {Jsm.Opcode.RANIME, (p, s) => new RANIME(p, s)},
            {Jsm.Opcode.RANIMEKEEP, (p, s) => new RANIMEKEEP(p, s)},
            {Jsm.Opcode.RCANIME, (p, s) => new RCANIME(p, s)},
            {Jsm.Opcode.RCANIMEKEEP, (p, s) => new RCANIMEKEEP(p, s)},
            {Jsm.Opcode.RANIMELOOP, (p, s) => new RANIMELOOP(p, s)},
            {Jsm.Opcode.RCANIMELOOP, (p, s) => new RCANIMELOOP(p, s)},
            {Jsm.Opcode.LADDERANIME, (p, s) => new LADDERANIME(p, s)},
            {Jsm.Opcode.DISCJUMP, (p, s) => new DISCJUMP(p, s)},
            {Jsm.Opcode.SETLINE, (p, s) => new SETLINE(p, s)},
            {Jsm.Opcode.LINEON, (p, s) => new LINEON(p, s)},
            {Jsm.Opcode.LINEOFF, (p, s) => new LINEOFF(p, s)},
            {Jsm.Opcode.WAIT, (p, s) => new WAIT(p, s)},
            {Jsm.Opcode.MSPEED, (p, s) => new MSPEED(p, s)},
            {Jsm.Opcode.MOVE, (p, s) => new MOVE(p, s)},
            {Jsm.Opcode.MOVEA, (p, s) => new MOVEA(p, s)},
            {Jsm.Opcode.PMOVEA, (p, s) => new PMOVEA(p, s)},
            {Jsm.Opcode.CMOVE, (p, s) => new CMOVE(p, s)},
            {Jsm.Opcode.FMOVE, (p, s) => new FMOVE(p, s)},
            {Jsm.Opcode.PJUMPA, (p, s) => new PJUMPA(p, s)},
            {Jsm.Opcode.ANIMESYNC, (p, s) => new ANIMESYNC(p, s)},
            {Jsm.Opcode.ANIMESTOP, (p, s) => new ANIMESTOP(p, s)},
            //{Opcode.MESW, (p, s) => new MESW(p, s)},
            {Jsm.Opcode.MES, (p, s) => new MES(p, s)},
            {Jsm.Opcode.MESSYNC, (p, s) => new MESSYNC(p, s)},
            {Jsm.Opcode.MESVAR, (p, s) => new MESVAR(p, s)},
            {Jsm.Opcode.ASK, (p, s) => new ASK(p, s)},
            {Jsm.Opcode.WINSIZE, (p, s) => new WINSIZE(p, s)},
            {Jsm.Opcode.WINCLOSE, (p, s) => new WINCLOSE(p, s)},
            {Jsm.Opcode.UCON, (p, s) => new UCON(p, s)},
            {Jsm.Opcode.UCOFF, (p, s) => new UCOFF(p, s)},
            {Jsm.Opcode.MOVIE, (p, s) => new MOVIE(p, s)},
            {Jsm.Opcode.MOVIESYNC, (p, s) => new MOVIESYNC(p, s)},
            {Jsm.Opcode.SETPC, (p, s) => new SETPC(p, s)},
            {Jsm.Opcode.DIR, (p, s) => new DIR(p, s)},
            {Jsm.Opcode.DIRP, (p, s) => new DIRP(p, s)},
            {Jsm.Opcode.DIRA, (p, s) => new DIRA(p, s)},
            {Jsm.Opcode.PDIRA, (p, s) => new PDIRA(p, s)},
            {Jsm.Opcode.SPUREADY, (p, s) => new SPUREADY(p, s)},
            {Jsm.Opcode.TALKON, (p, s) => new TALKON(p, s)},
            {Jsm.Opcode.TALKOFF, (p, s) => new TALKOFF(p, s)},
            {Jsm.Opcode.PUSHON, (p, s) => new PUSHON(p, s)},
            {Jsm.Opcode.PUSHOFF, (p, s) => new PUSHOFF(p, s)},
            {Jsm.Opcode.ISTOUCH, (p, s) => new ISTOUCH(p, s)},
            {Jsm.Opcode.MAPJUMPO, (p, s) => new MAPJUMPO(p, s)},
            {Jsm.Opcode.MAPJUMPON, (p, s) => new MAPJUMPON(p, s)},
            {Jsm.Opcode.MAPJUMPOFF, (p, s) => new MAPJUMPOFF(p, s)},
            {Jsm.Opcode.SETMESSPEED, (p, s) => new SETMESSPEED(p, s)},
            {Jsm.Opcode.SHOW, (p, s) => new SHOW(p, s)},
            {Jsm.Opcode.HIDE, (p, s) => new HIDE(p, s)},
            {Jsm.Opcode.TALKRADIUS, (p, s) => new TALKRADIUS(p, s)},
            {Jsm.Opcode.PUSHRADIUS, (p, s) => new PUSHRADIUS(p, s)},
            {Jsm.Opcode.AMESW, (p, s) => new AMESW(p, s)},
            {Jsm.Opcode.AMES, (p, s) => new AMES(p, s)},
            {Jsm.Opcode.GETINFO, (p, s) => new GETINFO(p, s)},
            {Jsm.Opcode.THROUGHON, (p, s) => new THROUGHON(p, s)},
            {Jsm.Opcode.THROUGHOFF, (p, s) => new THROUGHOFF(p, s)},
            {Jsm.Opcode.BATTLE, (p, s) => new BATTLE(p, s)},
            {Jsm.Opcode.BATTLERESULT, (p, s) => new BATTLERESULT(p, s)},
            {Jsm.Opcode.BATTLEON, (p, s) => new BATTLEON(p, s)},
            {Jsm.Opcode.BATTLEOFF, (p, s) => new BATTLEOFF(p, s)},
            {Jsm.Opcode.KEYSCAN, (p, s) => new KEYSCAN(p, s)},
            {Jsm.Opcode.KEYON, (p, s) => new KEYON(p, s)},
            {Jsm.Opcode.PGETINFO, (p, s) => new PGETINFO(p, s)},
            {Jsm.Opcode.DSCROLL, (p, s) => new DSCROLL(p, s)},
            {Jsm.Opcode.LSCROLL, (p, s) => new LSCROLL(p, s)},
            {Jsm.Opcode.CSCROLL, (p, s) => new CSCROLL(p, s)},
            {Jsm.Opcode.DSCROLLA, (p, s) => new DSCROLLA(p, s)},
            {Jsm.Opcode.LSCROLLA, (p, s) => new LSCROLLA(p, s)},
            {Jsm.Opcode.CSCROLLA, (p, s) => new CSCROLLA(p, s)},
            {Jsm.Opcode.SCROLLSYNC, (p, s) => new SCROLLSYNC(p, s)},
            {Jsm.Opcode.RMOVE, (p, s) => new RMOVE(p, s)},
            {Jsm.Opcode.RMOVEA, (p, s) => new RMOVEA(p, s)},
            {Jsm.Opcode.RPMOVEA, (p, s) => new RPMOVEA(p, s)},
            {Jsm.Opcode.RCMOVE, (p, s) => new RCMOVE(p, s)},
            {Jsm.Opcode.RFMOVE, (p, s) => new RFMOVE(p, s)},
            {Jsm.Opcode.MOVESYNC, (p, s) => new MOVESYNC(p, s)},
            {Jsm.Opcode.CLEAR, (p, s) => new CLEAR(p, s)},
            {Jsm.Opcode.DSCROLLP, (p, s) => new DSCROLLP(p, s)},
            {Jsm.Opcode.LSCROLLP, (p, s) => new LSCROLLP(p, s)},
            {Jsm.Opcode.CSCROLLP, (p, s) => new CSCROLLP(p, s)},
            {Jsm.Opcode.LTURNR, (p, s) => new LTURNR(p, s)},
            {Jsm.Opcode.LTURNL, (p, s) => new LTURNL(p, s)},
            {Jsm.Opcode.CTURNR, (p, s) => new CTURNR(p, s)},
            {Jsm.Opcode.CTURNL, (p, s) => new CTURNL(p, s)},
            {Jsm.Opcode.ADDPARTY, (p, s) => new ADDPARTY(p, s)},
            {Jsm.Opcode.SUBPARTY, (p, s) => new SUBPARTY(p, s)},
            {Jsm.Opcode.CHANGEPARTY, (p, s) => new CHANGEPARTY(p, s)},
            {Jsm.Opcode.REFRESHPARTY, (p, s) => new REFRESHPARTY(p, s)},
            {Jsm.Opcode.SETPARTY, (p, s) => new SETPARTY(p, s)},
            {Jsm.Opcode.ISPARTY, (p, s) => new ISPARTY(p, s)},
            {Jsm.Opcode.ADDMEMBER, (p, s) => new ADDMEMBER(p, s)},
            {Jsm.Opcode.SUBMEMBER, (p, s) => new SUBMEMBER(p, s)},
            //{Opcode.ISMEMBER, (p, s) => new ISMEMBER(p, s)},
            {Jsm.Opcode.LTURN, (p, s) => new LTURN(p, s)},
            {Jsm.Opcode.CTURN, (p, s) => new CTURN(p, s)},
            {Jsm.Opcode.PLTURN, (p, s) => new PLTURN(p, s)},
            {Jsm.Opcode.PCTURN, (p, s) => new PCTURN(p, s)},
            {Jsm.Opcode.JOIN, (p, s) => new JOIN(p, s)},
            //{Opcode.MESFORCUS, (p, s) => new MESFORCUS(p, s)},
            {Jsm.Opcode.BGANIME, (p, s) => new BGANIME(p, s)},
            {Jsm.Opcode.RBGANIME, (p, s) => new RBGANIME(p, s)},
            {Jsm.Opcode.RBGANIMELOOP, (p, s) => new RBGANIMELOOP(p, s)},
            {Jsm.Opcode.BGANIMESYNC, (p, s) => new BGANIMESYNC(p, s)},
            {Jsm.Opcode.BGDRAW, (p, s) => new BGDRAW(p, s)},
            {Jsm.Opcode.BGOFF, (p, s) => new BGOFF(p, s)},
            {Jsm.Opcode.BGANIMESPEED, (p, s) => new BGANIMESPEED(p, s)},
            {Jsm.Opcode.SETTIMER, (p, s) => new SETTIMER(p, s)},
            {Jsm.Opcode.DISPTIMER, (p, s) => new DISPTIMER(p, s)},
            //{Opcode.SHADETIMER, (p, s) => new SHADETIMER(p, s)},
            {Jsm.Opcode.SETGETA, (p, s) => new SETGETA(p, s)},
            {Jsm.Opcode.SETROOTTRANS, (p, s) => new SETROOTTRANS(p, s)},
            {Jsm.Opcode.SETVIBRATE, (p, s) => new SETVIBRATE(p, s)},
            //{Opcode.STOPVIBRATE, (p, s) => new STOPVIBRATE(p, s)},
            {Jsm.Opcode.MOVIEREADY, (p, s) => new MOVIEREADY(p, s)},
            {Jsm.Opcode.GETTIMER, (p, s) => new GETTIMER(p, s)},
            {Jsm.Opcode.FADEIN, (p, s) => new FADEIN(p, s)},
            {Jsm.Opcode.FADEOUT, (p, s) => new FADEOUT(p, s)},
            {Jsm.Opcode.FADESYNC, (p, s) => new FADESYNC(p, s)},
            {Jsm.Opcode.SHAKE, (p, s) => new SHAKE(p, s)},
            {Jsm.Opcode.SHAKEOFF, (p, s) => new SHAKEOFF(p, s)},
            {Jsm.Opcode.FADEBLACK, (p, s) => new FADEBLACK(p, s)},
            {Jsm.Opcode.FOLLOWOFF, (p, s) => new FOLLOWOFF(p, s)},
            {Jsm.Opcode.FOLLOWON, (p, s) => new FOLLOWON(p, s)},
            {Jsm.Opcode.GAMEOVER, (p, s) => new GAMEOVER(p, s)},
            //{Opcode.ENDING, (p, s) => new ENDING(p, s)},
            {Jsm.Opcode.SHADELEVEL, (p, s) => new SHADELEVEL(p, s)},
            {Jsm.Opcode.SHADEFORM, (p, s) => new SHADEFORM(p, s)},
            {Jsm.Opcode.FMOVEA, (p, s) => new FMOVEA(p, s)},
            //{Opcode.FMOVEP, (p, s) => new FMOVEP(p, s)},
            {Jsm.Opcode.SHADESET, (p, s) => new SHADESET(p, s)},
            {Jsm.Opcode.MUSICCHANGE, (p, s) => new MUSICCHANGE(p, s)},
            {Jsm.Opcode.MUSICLOAD, (p, s) => new MUSICLOAD(p, s)},
            {Jsm.Opcode.FADENONE, (p, s) => new FADENONE(p, s)},
            {Jsm.Opcode.POLYCOLOR, (p, s) => new POLYCOLOR(p, s)},
            {Jsm.Opcode.POLYCOLORALL, (p, s) => new POLYCOLORALL(p, s)},
            {Jsm.Opcode.KILLTIMER, (p, s) => new KILLTIMER(p, s)},
            {Jsm.Opcode.CROSSMUSIC, (p, s) => new CROSSMUSIC(p, s)},
            {Jsm.Opcode.DUALMUSIC, (p, s) => new DUALMUSIC(p, s)},
            {Jsm.Opcode.EFFECTPLAY, (p, s) => new EFFECTPLAY(p, s)},
            {Jsm.Opcode.EFFECTLOAD, (p, s) => new EFFECTLOAD(p, s)},
            {Jsm.Opcode.LOADSYNC, (p, s) => new LOADSYNC(p, s)},
            {Jsm.Opcode.MUSICSTOP, (p, s) => new MUSICSTOP(p, s)},
            {Jsm.Opcode.MUSICVOL, (p, s) => new MUSICVOL(p, s)},
            {Jsm.Opcode.MUSICVOLTRANS, (p, s) => new MUSICVOLTRANS(p, s)},
            {Jsm.Opcode.MUSICVOLFADE, (p, s) => new MUSICVOLFADE(p, s)},
            {Jsm.Opcode.ALLSEVOL, (p, s) => new ALLSEVOL(p, s)},
            {Jsm.Opcode.ALLSEVOLTRANS, (p, s) => new ALLSEVOLTRANS(p, s)},
            //{Opcode.ALLSEPOS, (p, s) => new ALLSEPOS(p, s)},
            //{Opcode.ALLSEPOSTRANS, (p, s) => new ALLSEPOSTRANS(p, s)},
            {Jsm.Opcode.SEVOL, (p, s) => new SEVOL(p, s)},
            {Jsm.Opcode.SEVOLTRANS, (p, s) => new SEVOLTRANS(p, s)},
            {Jsm.Opcode.SEPOS, (p, s) => new SEPOS(p, s)},
            {Jsm.Opcode.SEPOSTRANS, (p, s) => new SEPOSTRANS(p, s)},
            {Jsm.Opcode.SETBATTLEMUSIC, (p, s) => new SETBATTLEMUSIC(p, s)},
            {Jsm.Opcode.BATTLEMODE, (p, s) => new BATTLEMODE(p, s)},
            {Jsm.Opcode.SESTOP, (p, s) => new SESTOP(p, s)},
            //{Opcode.BGANIMEFLAG, (p, s) => new BGANIMEFLAG(p, s)},
            {Jsm.Opcode.INITSOUND, (p, s) => new INITSOUND(p, s)},
            {Jsm.Opcode.BGSHADE, (p, s) => new BGSHADE(p, s)},
            {Jsm.Opcode.BGSHADESTOP, (p, s) => new BGSHADESTOP(p, s)},
            {Jsm.Opcode.RBGSHADELOOP, (p, s) => new RBGSHADELOOP(p, s)},
            {Jsm.Opcode.DSCROLL2, (p, s) => new DSCROLL2(p, s)},
            {Jsm.Opcode.LSCROLL2, (p, s) => new LSCROLL2(p, s)},
            {Jsm.Opcode.CSCROLL2, (p, s) => new CSCROLL2(p, s)},
            {Jsm.Opcode.DSCROLLA2, (p, s) => new DSCROLLA2(p, s)},
            //{Opcode.LSCROLLA2, (p, s) => new LSCROLLA2(p, s)},
            {Jsm.Opcode.CSCROLLA2, (p, s) => new CSCROLLA2(p, s)},
            //{Opcode.DSCROLLP2, (p, s) => new DSCROLLP2(p, s)},
            //{Opcode.LSCROLLP2, (p, s) => new LSCROLLP2(p, s)},
            //{Opcode.CSCROLLP2, (p, s) => new CSCROLLP2(p, s)},
            {Jsm.Opcode.SCROLLSYNC2, (p, s) => new SCROLLSYNC2(p, s)},
            {Jsm.Opcode.SCROLLMODE2, (p, s) => new SCROLLMODE2(p, s)},
            {Jsm.Opcode.MENUENABLE, (p, s) => new MENUENABLE(p, s)},
            {Jsm.Opcode.MENUDISABLE, (p, s) => new MENUDISABLE(p, s)},
            {Jsm.Opcode.FOOTSTEPON, (p, s) => new FOOTSTEPON(p, s)},
            {Jsm.Opcode.FOOTSTEPOFF, (p, s) => new FOOTSTEPOFF(p, s)},
            {Jsm.Opcode.FOOTSTEPOFFALL, (p, s) => new FOOTSTEPOFFALL(p, s)},
            {Jsm.Opcode.FOOTSTEPCUT, (p, s) => new FOOTSTEPCUT(p, s)},
            {Jsm.Opcode.PREMAPJUMP, (p, s) => new PREMAPJUMP(p, s)},
            {Jsm.Opcode.USE, (p, s) => new USE(p, s)},
            {Jsm.Opcode.SPLIT, (p, s) => new SPLIT(p, s)},
            {Jsm.Opcode.ANIMESPEED, (p, s) => new ANIMESPEED(p, s)},
            {Jsm.Opcode.RND, (p, s) => new RND(p, s)},
            {Jsm.Opcode.DCOLADD, (p, s) => new DCOLADD(p, s)},
            {Jsm.Opcode.DCOLSUB, (p, s) => new DCOLSUB(p, s)},
            {Jsm.Opcode.TCOLADD, (p, s) => new TCOLADD(p, s)},
            {Jsm.Opcode.TCOLSUB, (p, s) => new TCOLSUB(p, s)},
            {Jsm.Opcode.FCOLADD, (p, s) => new FCOLADD(p, s)},
            {Jsm.Opcode.FCOLSUB, (p, s) => new FCOLSUB(p, s)},
            {Jsm.Opcode.COLSYNC, (p, s) => new COLSYNC(p, s)},
            {Jsm.Opcode.DOFFSET, (p, s) => new DOFFSET(p, s)},
            {Jsm.Opcode.LOFFSETS, (p, s) => new LOFFSETS(p, s)},
            {Jsm.Opcode.COFFSETS, (p, s) => new COFFSETS(p, s)},
            {Jsm.Opcode.LOFFSET, (p, s) => new LOFFSET(p, s)},
            {Jsm.Opcode.COFFSET, (p, s) => new COFFSET(p, s)},
            {Jsm.Opcode.OFFSETSYNC, (p, s) => new OFFSETSYNC(p, s)},
            {Jsm.Opcode.RUNENABLE, (p, s) => new RUNENABLE(p, s)},
            {Jsm.Opcode.RUNDISABLE, (p, s) => new RUNDISABLE(p, s)},
            {Jsm.Opcode.MAPFADEOFF, (p, s) => new MAPFADEOFF(p, s)},
            {Jsm.Opcode.MAPFADEON, (p, s) => new MAPFADEON(p, s)},
            {Jsm.Opcode.INITTRACE, (p, s) => new INITTRACE(p, s)},
            {Jsm.Opcode.SETDRESS, (p, s) => new SETDRESS(p, s)},
            //{Opcode.GETDRESS, (p, s) => new GETDRESS(p, s)},
            {Jsm.Opcode.FACEDIR, (p, s) => new FACEDIR(p, s)},
            {Jsm.Opcode.FACEDIRA, (p, s) => new FACEDIRA(p, s)},
            {Jsm.Opcode.FACEDIRP, (p, s) => new FACEDIRP(p, s)},
            {Jsm.Opcode.FACEDIRLIMIT, (p, s) => new FACEDIRLIMIT(p, s)},
            {Jsm.Opcode.FACEDIROFF, (p, s) => new FACEDIROFF(p, s)},
            {Jsm.Opcode.SARALYOFF, (p, s) => new SARALYOFF(p, s)},
            {Jsm.Opcode.SARALYON, (p, s) => new SARALYON(p, s)},
            {Jsm.Opcode.SARALYDISPOFF, (p, s) => new SARALYDISPOFF(p, s)},
            {Jsm.Opcode.SARALYDISPON, (p, s) => new SARALYDISPON(p, s)},
            {Jsm.Opcode.MESMODE, (p, s) => new MESMODE(p, s)},
            {Jsm.Opcode.FACEDIRINIT, (p, s) => new FACEDIRINIT(p, s)},
            {Jsm.Opcode.FACEDIRI, (p, s) => new FACEDIRI(p, s)},
            {Jsm.Opcode.JUNCTION, (p, s) => new JUNCTION(p, s)},
            {Jsm.Opcode.SETCAMERA, (p, s) => new SETCAMERA(p, s)},
            {Jsm.Opcode.BATTLECUT, (p, s) => new BATTLECUT(p, s)},
            {Jsm.Opcode.FOOTSTEPCOPY, (p, s) => new FOOTSTEPCOPY(p, s)},
            {Jsm.Opcode.WORLDMAPJUMP, (p, s) => new WORLDMAPJUMP(p, s)},
            //{Opcode.RFACEDIRI, (p, s) => new RFACEDIRI(p, s)},
            {Jsm.Opcode.RFACEDIR, (p, s) => new RFACEDIR(p, s)},
            {Jsm.Opcode.RFACEDIRA, (p, s) => new RFACEDIRA(p, s)},
            {Jsm.Opcode.RFACEDIRP, (p, s) => new RFACEDIRP(p, s)},
            {Jsm.Opcode.RFACEDIROFF, (p, s) => new RFACEDIROFF(p, s)},
            {Jsm.Opcode.FACEDIRSYNC, (p, s) => new FACEDIRSYNC(p, s)},
            {Jsm.Opcode.COPYINFO, (p, s) => new COPYINFO(p, s)},
            //{Opcode.PCOPYINFO, (p, s) => new PCOPYINFO(p, s)},
            {Jsm.Opcode.RAMESW, (p, s) => new RAMESW(p, s)},
            {Jsm.Opcode.BGSHADEOFF, (p, s) => new BGSHADEOFF(p, s)},
            {Jsm.Opcode.AXIS, (p, s) => new AXIS(p, s)},
            //{Opcode.AXISSYNC, (p, s) => new AXISSYNC(p, s)},
            {Jsm.Opcode.MENUNORMAL, (p, s) => new MENUNORMAL(p, s)},
            {Jsm.Opcode.MENUPHS, (p, s) => new MENUPHS(p, s)},
            {Jsm.Opcode.BGCLEAR, (p, s) => new BGCLEAR(p, s)},
            {Jsm.Opcode.GETPARTY, (p, s) => new GETPARTY(p, s)},
            {Jsm.Opcode.MENUSHOP, (p, s) => new MENUSHOP(p, s)},
            {Jsm.Opcode.DISC, (p, s) => new DISC(p, s)},
            //{Opcode.DSCROLL3, (p, s) => new DSCROLL3(p, s)},
            {Jsm.Opcode.LSCROLL3, (p, s) => new LSCROLL3(p, s)},
            //{Opcode.CSCROLL3, (p, s) => new CSCROLL3(p, s)},
            {Jsm.Opcode.MACCEL, (p, s) => new MACCEL(p, s)},
            {Jsm.Opcode.MLIMIT, (p, s) => new MLIMIT(p, s)},
            {Jsm.Opcode.ADDITEM, (p, s) => new ADDITEM(p, s)},
            {Jsm.Opcode.SETWITCH, (p, s) => new SETWITCH(p, s)},
            {Jsm.Opcode.SETODIN, (p, s) => new SETODIN(p, s)},
            {Jsm.Opcode.RESETGF, (p, s) => new RESETGF(p, s)},
            {Jsm.Opcode.MENUNAME, (p, s) => new MENUNAME(p, s)},
            {Jsm.Opcode.REST, (p, s) => new REST(p, s)},
            {Jsm.Opcode.MOVECANCEL, (p, s) => new MOVECANCEL(p, s)},
            //{Opcode.PMOVECANCEL, (p, s) => new PMOVECANCEL(p, s)},
            {Jsm.Opcode.ACTORMODE, (p, s) => new ACTORMODE(p, s)},
            {Jsm.Opcode.MENUSAVE, (p, s) => new MENUSAVE(p, s)},
            {Jsm.Opcode.SAVEENABLE, (p, s) => new SAVEENABLE(p, s)},
            {Jsm.Opcode.PHSENABLE, (p, s) => new PHSENABLE(p, s)},
            {Jsm.Opcode.HOLD, (p, s) => new HOLD(p, s)},
            {Jsm.Opcode.MOVIECUT, (p, s) => new MOVIECUT(p, s)},
            {Jsm.Opcode.SETPLACE, (p, s) => new SETPLACE(p, s)},
            {Jsm.Opcode.SETDCAMERA, (p, s) => new SETDCAMERA(p, s)},
            {Jsm.Opcode.CHOICEMUSIC, (p, s) => new CHOICEMUSIC(p, s)},
            {Jsm.Opcode.GETCARD, (p, s) => new GETCARD(p, s)},
            {Jsm.Opcode.DRAWPOINT, (p, s) => new DRAWPOINT(p, s)},
            {Jsm.Opcode.PHSPOWER, (p, s) => new PHSPOWER(p, s)},
            {Jsm.Opcode.KEY, (p, s) => new KEY(p, s)},
            {Jsm.Opcode.CARDGAME, (p, s) => new CARDGAME(p, s)},
            {Jsm.Opcode.SETBAR, (p, s) => new SETBAR(p, s)},
            {Jsm.Opcode.DISPBAR, (p, s) => new DISPBAR(p, s)},
            {Jsm.Opcode.KILLBAR, (p, s) => new KILLBAR(p, s)},
            {Jsm.Opcode.SCROLLRATIO2, (p, s) => new SCROLLRATIO2(p, s)},
            {Jsm.Opcode.WHOAMI, (p, s) => new WHOAMI(p, s)},
            {Jsm.Opcode.MUSICSTATUS, (p, s) => new MUSICSTATUS(p, s)},
            {Jsm.Opcode.MUSICREPLAY, (p, s) => new MUSICREPLAY(p, s)},
            {Jsm.Opcode.DOORLINEOFF, (p, s) => new DOORLINEOFF(p, s)},
            {Jsm.Opcode.DOORLINEON, (p, s) => new DOORLINEON(p, s)},
            {Jsm.Opcode.MUSICSKIP, (p, s) => new MUSICSKIP(p, s)},
            {Jsm.Opcode.DYING, (p, s) => new DYING(p, s)},
            {Jsm.Opcode.SETHP, (p, s) => new SETHP(p, s)},
            //{Opcode.GETHP, (p, s) => new GETHP(p, s)},
            {Jsm.Opcode.MOVEFLUSH, (p, s) => new MOVEFLUSH(p, s)},
            {Jsm.Opcode.MUSICVOLSYNC, (p, s) => new MUSICVOLSYNC(p, s)},
            {Jsm.Opcode.PUSHANIME, (p, s) => new PUSHANIME(p, s)},
            {Jsm.Opcode.POPANIME, (p, s) => new POPANIME(p, s)},
            {Jsm.Opcode.KEYSCAN2, (p, s) => new KEYSCAN2(p, s)},
            //{Opcode.KEYON2, (p, s) => new KEYON2(p, s)},
            {Jsm.Opcode.PARTICLEON, (p, s) => new PARTICLEON(p, s)},
            {Jsm.Opcode.PARTICLEOFF, (p, s) => new PARTICLEOFF(p, s)},
            {Jsm.Opcode.KEYSIGHNCHANGE, (p, s) => new KEYSIGHNCHANGE(p, s)},
            {Jsm.Opcode.ADDGIL, (p, s) => new ADDGIL(p, s)},
            {Jsm.Opcode.ADDPASTGIL, (p, s) => new ADDPASTGIL(p, s)},
            {Jsm.Opcode.ADDSEEDLEVEL, (p, s) => new ADDSEEDLEVEL(p, s)},
            {Jsm.Opcode.PARTICLESET, (p, s) => new PARTICLESET(p, s)},
            {Jsm.Opcode.SETDRAWPOINT, (p, s) => new SETDRAWPOINT(p, s)},
            {Jsm.Opcode.MENUTIPS, (p, s) => new MENUTIPS(p, s)},
            {Jsm.Opcode.LASTIN, (p, s) => new LASTIN(p, s)},
            {Jsm.Opcode.LASTOUT, (p, s) => new LASTOUT(p, s)},
            {Jsm.Opcode.SEALEDOFF, (p, s) => new SEALEDOFF(p, s)},
            {Jsm.Opcode.MENUTUTO, (p, s) => new MENUTUTO(p, s)},
            //{Opcode.OPENEYES, (p, s) => new OPENEYES(p, s)},
            {Jsm.Opcode.CLOSEEYES, (p, s) => new CLOSEEYES(p, s)},
            //{Opcode.BLINKEYES, (p, s) => new BLINKEYES(p, s)},
            {Jsm.Opcode.SETCARD, (p, s) => new SETCARD(p, s)},
            {Jsm.Opcode.HOWMANYCARD, (p, s) => new HOWMANYCARD(p, s)},
            {Jsm.Opcode.WHERECARD, (p, s) => new WHERECARD(p, s)},
            {Jsm.Opcode.ADDMAGIC, (p, s) => new ADDMAGIC(p, s)},
            {Jsm.Opcode.SWAP, (p, s) => new SWAP(p, s)},
            //{Opcode.SETPARTY2, (p, s) => new SETPARTY2(p, s)},
            {Jsm.Opcode.SPUSYNC, (p, s) => new SPUSYNC(p, s)},
            {Jsm.Opcode.BROKEN, (p, s) => new BROKEN(p, s)},
            {Jsm.Opcode.Unknown1, (p, s) => new Unknown1(p, s)},
            {Jsm.Opcode.Unknown2, (p, s) => new Unknown2(p, s)},
            {Jsm.Opcode.Unknown3, (p, s) => new Unknown3(p, s)},
            {Jsm.Opcode.Unknown4, (p, s) => new Unknown4(p, s)},
            {Jsm.Opcode.Unknown5, (p, s) => new Unknown5(p, s)},
            {Jsm.Opcode.Unknown6, (p, s) => new Unknown6(p, s)},
            {Jsm.Opcode.Unknown7, (p, s) => new Unknown7(p, s)},
            {Jsm.Opcode.Unknown8, (p, s) => new Unknown8(p, s)},
            {Jsm.Opcode.Unknown9, (p, s) => new Unknown9(p, s)},
            {Jsm.Opcode.Unknown10, (p, s) => new Unknown10(p, s)},
            {Jsm.Opcode.Unknown11, (p, s) => new Unknown11(p, s)},
            {Jsm.Opcode.Unknown12, (p, s) => new Unknown12(p, s)},
            {Jsm.Opcode.Unknown13, (p, s) => new Unknown13(p, s)},
            {Jsm.Opcode.Unknown14, (p, s) => new Unknown14(p, s)},
            {Jsm.Opcode.Unknown15, (p, s) => new Unknown15(p, s)},
            {Jsm.Opcode.Unknown16, (p, s) => new Unknown16(p, s)},
            {Jsm.Opcode.PREMAPJUMP2, (p, s) => new PREMAPJUMP2(p, s)},
            {Jsm.Opcode.TUTO, (p, s) => new TUTO(p, s)}
        };
    }
}